version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  timescale:
    image: test:test
    restart: always
    hostname: timescale
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/csvs/cpu_usage.csv:/var/lib/postgresql/csvs/cpu_usage.csv
    <<: *logging


